### ISSUE TITLE
[HTTP/1.1 401 Unauthorized 691ms]

### ISSUE THREAD

**Issue by test2a** [apioo/fusio-docker#15]
unable to login. 

https://github.com/apioo/fusio/issues/438

i am not able to login to the backend
![Screenshot_20220213_213025](https://user-images.githubusercontent.com/39449563/153761639-4dbb8470-2ee5-49d0-9ebe-150367ab0730.png)

**Comment by chriskapp** [comment]
Hi, ok so the user which you have provided at the docker compose file is called "sdfsdf" and the password is also in sync with the user? Note if you have previously started the container with a different user the user will not change since the database setup was already executed, in this case you would need to delete your database and run again `docker-compose up -d` So in this case I would assume that you provide the wrong credentials to the backend. Otherwise you could also take a look into the database container at the `fusio_user` table to see which user is available.

**Comment by test2a** [comment]
no. the user was random. i had created the user "superuser" but same thing. yes, the screenshot is wrong credentials.

**Comment by test2a** [comment]
isnt the username/pw from docker-compose.yml?

FUSIO_BACKEND_USER: "user"

      FUSIO_BACKEND_EMAIL: "mail"

      FUSIO_BACKEND_PW: "pw"
