### ISSUE TITLE
memecache container not in docker-compose.yml

### ISSUE THREAD

**Issue by jmarshallpresnell** [apioo/fusio-docker#4]
A memcache container is mentioned in the readme, but is not in the docker-compose.yml file. Is this a real error or a doc error?

**Comment by chriskapp** [comment]
Hi, yes this is a documentation error, previosuly we have used a separate container for the memcache service but we have moved the service inside the Fusio image since otherwise a user needs to have 3 containers to run Fusio (Database, Memcache and Fusio). Now you only need Fusio and the Database container. But I will adjust the readme.

**Comment by jmarshallpresnell** [comment]
Thanks! :)
